version: '2'
services:
  spring:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - database
  database:
    image: postgres:10.4
    ports:
     - "5432:5432"
    environment:
     - POSTGRES_PASSWORD=st11u2ddb231
     - POSTGRES_USER=postgres
     - POSTGRES_DB=studdb
    volumes:
     - sample_db:/var/lib/postgresql/data
volumes:
    sample_db: {}
